project_name: diq
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - main: .
    binary: diq
    ldflags:
      - -s -w
      - -X github.com/litencatt/diq/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
    format_overrides:
      - goos: darwin
        format: zip
release:
  prerelease: auto
